- id: omni-ruff-sh
  name: copy ruff config (shell)
  description: Copy a global Ruff config file to project repo
  entry: hooks/copy_ruff_config_shell.sh
  language: script
- id: omni-ruff-py
  name: copy ruff config (python) 
  description: Copy a global Ruff config file to project repo
  entry: copy-ruff-config
  language: python
- id: omni-ruff-az
  name: clone ruff config (azure)
  description: Clone a global Ruff config file to project repo
  entry: clone-ruff-config
  language: python
  # args: ['--config', 'pyproject.toml']