default_stages: [ commit ]
files: ^.
repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.6.0
  #   hooks:
  #     - id: check-yaml
  #     - id: check-added-large-files
  #     - id: check-case-conflict
  #     - id: mixed-line-ending
  #     - id: check-merge-conflict
  #     - id: check-ast
  #     - id: check-docstring-first
  #     - id: check-vcs-permalinks
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: "v0.41.0"
  #   hooks:
  #     - id: markdownlint
  #       name: Lint - Markdown files
  #       args: ["-f"]
  #       stages: [commit]
  - repo: local
    hooks:
      - id: omni-ruff-py
        name: Copy a global Ruff config file to project repo
        entry: python hooks/copy_ruff_config.py
        language: python 
  - repo: local
    hooks:
      - id: omni-ruff-az
        name: Copy a global Ruff config file to project repo
        entry: python hooks/clone_ruff_config.py
        args: ['--config', 'pyproject.toml']
        language: python
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.4.8
  #   hooks:
  #     - id: ruff
  #       name: Ruff - linting checks
  #       types_or: [ python, pyi, jupyter ]
  #       args: [ --preview, --fix, --exit-non-zero-on-fix, --config, ruff.toml]
  #     - id: ruff-format
  #       name: Ruff - formatting checks
  #       types_or: [ python, pyi, jupyter ]
  #       args: [--config, ruff.toml, --preview ]
  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.18.3 # Make sure to also bump the azure-devops pipeline container resource to match this version for gitleaks container
  #   hooks:
  #     # this gitleaks hook runs LOCALLY in PROTECT mode, it is triggered when committing,and PREVENTS from introducing leaks
  #     # more info: https://github.com/gitleaks/gitleaks?tab=readme-ov-file#protect
  #     - id: gitleaks
  #       name: Security - GitLeaks - Protect (local)
  #       description: Protect from hardcoded secrets
  #       stages: [commit]
  #       entry: gitleaks protect --verbose --source=. --config=gitleaks.toml --baseline-path=gitleaks-report.json --redact --staged
  #       language: golang
  #     # this gitleaks hook runs REMOTELY (CI) in DETECT mode, it is triggered when running overall pre-commit hook, and NOTIFIES if leaks have been introduced (possibly earlier in git history)
  #     # more info: https://github.com/gitleaks/gitleaks?tab=readme-ov-file#detect
  #     - id: gitleaks-docker
  #       name: Security - GitLeaks - Detect (CI)
  #       description: Detect hardcoded secrets
  #       stages: [manual]
  #       entry: zricethezav/gitleaks detect --verbose --source=. --config=gitleaks.toml --redact --log-level trace
  #       language: docker_image          