- id: omni-ruff-sh
  name: Copy a global Ruff config file to project repo
  entry: hooks/copy_ruff_config_shell.sh
  language: script

- id: omni-ruff-py
  name: Copy a global Ruff config file to project repo
  entry: omni-ruff-py
  language: python